title: El sitio de LLMM. IESGC
author: @lmagarin
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Trabajando con repositorios
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
